name: CI/CD Git Pull Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo yum install nginx  -y
          cd /var/www/
          mkdir html
          cd html
          touch index.html
          git pull
          sudo systemctl restart nginx
